language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - travis_retry composer update ${COMPOSER_OPTS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

branches:
  only: master
